name: 'Policy Validation Action'
description: 'Validates OCI policy statements'
inputs:
  path:
    description: 'Path to policy file or directory'
    required: true
outputs:
  allow_segments:
    description: 'Found allow segments in policy'
runs:
  using: 'node16'
  main: 'dist/index.js'