name: 'OCI Policy Validator'
description: 'Validates OCI policy statements in Terraform configurations'
inputs:
  path:
    description: 'Path to policy file or directory'
    required: false
    default: '.'
  extractor:
    description: 'Type of policy extractor to use (regex, json)'
    required: false
    default: 'regex'
  extractorPattern:
    description: 'Custom pattern for the policy extractor'
    required: false
  exitOnError:
    description: 'Exit with error code if any policy is invalid'
    required: false
    default: 'true'
outputs:
  policy_expressions:
    description: 'List of validated policy expressions (Allow, Define, Endorse, Admit) found in policies'
runs:
  using: 'node20'
  main: 'lib/Main.js'