name: 'Policy Validation'
description: 'Validate policy statements in Terraform files'
inputs:
  path:
    description: 'Path to directory or file to scan'
    required: false
    default: '.'
  extractor:
    description: 'Type of extractor to use (regex, json)'
    required: false
    default: 'regex'
  extractorPattern:
    description: 'Custom pattern for regex extractor'
    required: false
  exitOnError:
    description: 'Exit immediately when an error is found'
    required: false
    default: 'true'
  files:
    description: 'Comma-separated list of specific files to scan'
    required: false
  validateCisBenchmark:
    description: 'Enable validation against OCI CIS Benchmark v2.0'
    required: false
    default: 'false'
outputs:
  policy_validation:
    description: 'Validation results in JSON format'
runs:
  using: 'node16'
  main: 'dist/index.js'