name: 'Policy Validation'
description: 'Validate policy statements in Terraform files'
inputs:
  path:
    description: 'Path to directory or file to scan'
    required: false
    default: '.'
  extractor:
    description: 'Type of extractor to use (regex, hcl)'
    required: false
    default: 'regex'
  pattern:
    description: 'Custom regex pattern for policy extraction'
    required: false
  exit-on-error:
    description: 'Exit with non-zero status if validation fails'
    required: false
    default: 'true'
  files:
    description: 'Comma-separated list of specific files to process'
    required: false
  file-extension:
    description: 'Filter files by specified extension (e.g., .tf)'
    required: false
  validators-local:
    description: 'Enable local (per-file) validators like syntax validation'
    required: false
    default: 'true'
  validators-global:
    description: 'Enable global validators like CIS benchmark'
    required: false
    default: 'true'
  agentic-validation-enabled:
    description: 'Enable the agentic (AI-powered) validator.'
    required: false
    default: 'false'
  agentic-validation-provider:
    description: "Specify the LLM provider (e.g., 'openai')."
    required: false
  agentic-validation-api-key:
    description: 'API key for the LLM provider.'
    required: false
outputs:
  results:
    description: 'Validation results in JSON format'
  error:
    description: 'Error message if the validation process fails'
runs:
  using: 'node20'
  main: 'dist/index.js'