name: 'OCI Policy Validator'
description: 'Validates OCI policy statements in Terraform configurations'
inputs:
  path:
    description: 'Path to policy file or directory'
    required: false
    default: '.'
outputs:
  policy_expressions:
    description: 'List of validated policy expressions (Allow, Define, Endorse, Admit) found in policies'
runs:
  using: 'node16'
  main: 'lib/Main.js'