image: node:16

definitions:
  steps:
    - step: &build
        name: Build
        clone:
          depth: full  # Ensure we have full repository access
        caches:
          - node
        script:
          - npm ci
          - npm run build
        artifacts:
          - dist/**

    - step: &test
        name: Test
        caches:
          - node
        script:
          - apt-get update && apt-get install -y jq
          - npm ci
          - npm run build
          
          # Run Jest tests with detailed reporting
          - |
            echo "Running Jest Tests..."
            mkdir -p test-results
            npm test || {
              echo "==== TEST FAILURES ===="
              if [ -f "test-results/test-results.xml" ]; then
                echo "Test Report Contents:"
                cat test-results/test-results.xml
              else
                echo "No test report found!"
              fi
              echo "======================="
              exit 1
            }
            
            if [ -f "test-results/test-results.xml" ]; then
              echo "Test Report Summary:"
              grep -A 1 "testsuites" test-results/test-results.xml
            fi
          
          # Create test policies
          - |
            mkdir -p test/policies
            cat > test/policies/valid.tf << 'EOL'
            resource "oci_identity_policy" "test_policy" {
              statements = [
                "Allow group Administrators to manage all-resources in tenancy",
                "Allow group Developers to use instances in compartment dev",
                "Define tenancy Acceptor as ocid1.tenancy.oc1..aaaaaa",
                "Endorse group NetworkAdmins to manage virtual-network-family in tenancy foo",
                "Admit group ServiceAdmins of tenancy accountFoo to manage instances in tenancy",
                "Allow group SecurityAdmins to manage all-resources in tenancy where request.user.groups in ('SecurityAdmins','NetworkAdmins')"
              ]
            }
            EOL

            cat > test/policies/invalid.tf << 'EOL'
            resource "oci_identity_policy" "invalid_policy" {
              statements = [
                "Allow BadSyntax manage",
                "Allow groupDevelopers to use instances in compartment dev",
                "Admit group of tenancy 123 to manage instances in foo"
              ]
            }
            EOL

            cat > test/policies/variable_interpolation.tf << 'EOL'
            resource "oci_identity_policy" "test_policy_vars" {
              statements = [
                "Allow group ${var.admin_group} to manage all-resources in tenancy",
                "Define tenancy ${var.tenant_name} as ${var.tenant_ocid}",
                "Endorse group ${var.network_admins} to manage virtual-network-family in tenancy foo",
                "Admit group ${var.dev_group} of tenancy accountFoo to use instances in compartment ${var.env}",
                "Allow any-user to use instances in compartment ${var.public_compartment} where request.time BETWEEN ${var.start_time} AND ${var.end_time}"
              ]
            }
            EOL
          # Updated verify_json with stricter type checking
          - |
            verify_json() {
              local output="$1"
              echo "$output" | grep -E '^\{.*\}$|^\[.*\]$' | tail -n1 | jq -e '
                if type=="object" then
                  (.error != null or (.isValid != null and (.errors|type)=="array"))
                elif type=="array" then
                  all(.[]; (type=="object" and (.isValid|type)=="boolean" and (.errors|type)=="array"))
                else
                  false
                end
              ' >/dev/null
            }
            
            for file in valid.tf invalid.tf variable_interpolation.tf; do
              echo "Testing $file..."
              if OUTPUT=$(node dist/index.js validate test/policies/$file 2>&1); then
                if ! verify_json "$OUTPUT"; then
                  echo "Invalid JSON output for $file"
                  echo "$OUTPUT"
                  exit 1
                fi
              else
                if ! verify_json "$OUTPUT"; then
                  echo "Invalid JSON output for failed case $file"
                  echo "$OUTPUT"
                  exit 1
                fi
              fi
            done
        
        artifacts:
          reports:
            junit: test-results/test-results.xml
          when: always

pipelines:
  default:
    - step: *build
    - step: *test
  
  branches:
    main:
      - step: *build
      - step: *test
      - step:
          name: Publish
          deployment: production
          script:
            - npm ci
            - npm version ${BITBUCKET_TAG}
            - npm publish
          condition:
            changesets:
              includePaths:
                - "**"
              includeTags:
                - "^v[0-9]+.[0-9]+.[0-9]+$"

  pull-requests:
    '**':
      - step: *build
      - step: *test

custom:
  release:
    - step: *build
    - step: *test
    - step:
        name: Publish to NPM
        script:
          - pipe: atlassian/npm-publish:0.3.0
            variables:
              NPM_TOKEN: $NPM_TOKEN
caches:
  node: ~/.npm
