name: Release Package

on:
  push:
    branches:
      - main
      - development
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js for publishing
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: ${{ github.ref == 'refs/heads/main' && 'https://registry.npmjs.org' || 'https://npm.pkg.github.com' }}
          scope: "@gtrevorrow"
          
      - run: npm ci
      - run: npm run build
          
      - name: Publish Package
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            npm publish --access public
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            npm publish --tag beta
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}